name: Node.js CI

on:
    # This will trigger on all pushes to all branches.
  push: {}
  # Alternatively, you can only trigger if commits are pushed to certain branches, e.g.:
  # push:
  #   branches:
  #     - master
  #     - unstable

    # This will trigger on all pushes to all branches.
  pull: {}
  # Alternatively, you can only trigger if commits are pushed to certain branches, e.g.:
  # pull:
  #   branches:
  #     - master
  #     - unstable
  #push:
  #  branches: [ master ]
  #pull_request:
  #  branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
   # - run: npm test
    - run: npm run deploy:ci --if-present

      env:
        CI: true
        GITHUB_TOKEN : ${{ secrets.G_T}}
        ## APP: ${{env.APP}}				 
        # Deploy env
        # HOST: ${{ secrets.HOST }}
        # PASS: ${{ secrets.PASS }}
        # USER: ${{ secrets.USER }}